// Generated by CoffeeScript 1.9.2
(function() {
  var Mailer, configs, nodemailer, xoauth2;

  nodemailer = require('nodemailer');

  xoauth2 = require('xoauth2');

  configs = require('konfig')();

  module.exports = Mailer = (function() {
    function Mailer(params) {
      var generator;
      this.mailOpts = {
        from: configs.app.MAIL_FROM,
        to: params.to,
        subject: params.subject,
        html: params.html
      };
      generator = xoauth2.createXOAuth2Generator({
        user: configs.app.MAIL_AUTH.user,
        clientId: configs.app.GOOGLE_AUTH.CLIENT_ID,
        clientSecret: configs.app.GOOGLE_AUTH.CLIENT_SECRET,
        refreshToken: configs.app.GOOGLE_AUTH.REFRESH_TOKEN,
        accessToken: configs.app.GOOGLE_AUTH.ACCESS_TOKEN
      });
      generator.on('token', function(token) {
        console.log('New token for %s: %s', token.user, token.accessToken);
      });
      this.transporter = nodemailer.createTransport({
        service: configs.app.MAIL_SERVICE,
        auth: {
          xoauth2: generator
        }
      });
    }

    Mailer.prototype.send = function() {
      return new Promise((function(_this) {
        return function(resolve, reject) {
          return _this.transporter.sendMail(_this.mailOpts, function(err, info) {
            if (err) {
              console.log(err);
              _this.transporter.close();
              return reject(err);
            }
            console.log('Message sent: ', info.response);
            _this.transporter.close();
            return resolve(info);
          });
        };
      })(this));
    };

    return Mailer;

  })();

}).call(this);
