// Generated by CoffeeScript 1.9.2
(function() {
  var request;

  request = require('request');

  (function() {
    var loadBase64Data;
    loadBase64Data = function(url) {
      return new Promise(function(resolve, reject) {
        return request({
          url: url,
          encoding: null
        }, function(err, res, body) {
          var base64prefix, image;
          if (!err && res.statusCode === 200) {
            base64prefix = 'data:' + res.headers['content-type'] + ';base64,';
            image = body.toString('base64');
            return resolve(base64prefix + image);
          } else {
            return reject(err);
          }
        });
      });
    };
    return exports.myUtil = {
      loadBase64Data: loadBase64Data
    };
  }).call(this);

}).call(this);
