// Generated by CoffeeScript 1.9.2
(function() {
  var Mailer, configs, fs, my, path, redis, request;

  path = require('path');

  fs = require('fs');

  redis = require('redis');

  request = require('superagent');

  configs = require('konfig')();

  Mailer = require(path.resolve('js', 'Mailer'));

  my = require(path.resolve('js', 'my')).my;

  module.exports = function(app) {
    var createHTMLForMail, getHistory, saveHistory, sendMail;
    getHistory = function() {
      return new Promise(function(resolve, reject) {
        return redisClient.lrange(REDIS_HISTORY, 0, -1, function(err, items) {
          if (err) {
            console.error(err);
          }
          return resolve(items);
        });
      });
    };
    saveHistory = function(value) {
      return redisClient.rpush(REDIS_HISTORY, value);
    };
    createHTMLForMail = function(err, body, response) {
      return "<p>Assis-waifu2x Error</p>\n<h1>ERR</h1>\n<p>" + err + "</p>\n<hr>\n<h1>BODY</h1>\n<p>" + body.url + "</p>\n<hr>\n<h1>Response</h1>\n<p>" + response.error + "</p>\n<p>" + response.text + "</p>";
    };
    sendMail = function(err, body, response) {
      var mailer, params;
      params = {
        to: configs.app.MAIL_TO,
        subject: 'Assist-waifu2x Error',
        html: createHTMLForMail(err, body, response)
      };
      mailer = new Mailer(params);
      return mailer.send().then(function(result) {
        return res.json({
          result: result,
          body: body,
          error: response.error
        });
      })["catch"](function(err) {
        return res.json({
          err: err
        });
      });
    };
    app.get('/api/history/list', function(req, res) {
      getHistory().then(function(items) {
        return res.json({
          history: items
        });
      });
    });
    return app.post('/api/download/waifu2x', function(req, res) {
      var sendOption;
      console.log('Go convert!!', req.body);
      console.time("/api/download/waifu2x");
      sendOption = {
        'url': req.body.url,
        'noise': req.body.noise - 0,
        'scale': req.body.scale - 0,
        'style': req.body.style
      };
      request.post('http://waifu2x.udp.jp/api').type('form').send(sendOption).end(function(err, response) {
        if (err) {
          console.log('err = ', err);
          sendMail(err, req.body, response);
          res.json({
            body: req.body,
            error: response.error
          });
          return;
        }
        console.log('res = ', response);
        console.log('res.type = ', response.type);
        console.timeEnd("/api/download/waifu2x");
        return res.json({
          body: response.body,
          type: response.type
        });
      });
    });
  };

}).call(this);
