// Generated by CoffeeScript 1.9.2
(function() {
  var path;

  path = require('path');

  module.exports = function(app) {
    app.get('/', function(req, res) {
      res.sendFile(path.resolve('public', 'index.html'));
    });
    return app.get('/history', function(req, res) {
      res.sendFile(path.resolve('public', 'history.html'));
    });
  };

}).call(this);
